Repository Team-DragMe/Drop-the-BE, pull requests merged in 2023-02, with the labels that each got.

#25 feat: 소셜 로그인 및 회원 가입, 토큰 재발급
  package.json
  src/config/index.ts
  src/controllers/AuthController.ts
  src/dtos/SocialUser.ts
  src/dtos/UserDto.ts
  src/entities/User.ts
  src/middleware/auth.ts
  src/modules/exceptionMessage.ts
  src/modules/jwtHandler.ts
  src/modules/responseMessage.ts
  src/services/AuthService.ts
  src/services/UserService.ts
  yarn.lock
Labels: enhancement, m1njae, feat

#20 feat: 계획블록 수정 API
  package.json
  src/controllers/PlanController.ts
  src/entities/Plan.ts
  src/entities/PlanOrder.ts
  src/entities/User.ts
  src/middleware/auth.ts
  src/middleware/errorValidator.ts
  src/modules/responseMessage.ts
  src/services/PlanService.ts
  yarn.lock
Labels: enhancement, m1njae, feat

#24 feat: 계획블록 생성
  package.json
  src/controllers/PlanController.ts
  src/entities/PlanOrder.ts
  src/middleware/errorValidator.ts
  src/modules/responseMessage.ts
  src/services/PlanService.ts
  yarn.lock
Labels: enhancement, m1njae, feat

#21 feat: 계획 블록 삭제
  src/controllers/PlanController.ts
  src/middleware/errorValidator.ts
  src/modules/responseMessage.ts
  src/services/PlanService.ts
Labels: enhancement, m1njae, feat

#29 feat: 계획블록 순서 이동 및 변경
  src/controllers/PlanController.ts
  src/middleware/errorValidator.ts
  src/modules/responseMessage.ts
  src/services/PlanService.ts
Labels: enhancement, m1njae, feat

#37 fix: 계획 블록 생성 로직 수정
  src/config/RoutingConfig.ts
  src/controllers/AuthController.ts
  src/middleware/errorGenerator.ts
  src/middleware/errorHandler.ts
  src/services/PlanService.ts
Labels: bug, m1njae

#35 feat: 날짜별 계획블록 존재여부 조회
  src/controllers/PlanController.ts
  src/middleware/errorValidator.ts
  src/modules/responseMessage.ts
  src/services/PlanService.ts
Labels: enhancement, m1njae, feat

#26 타임블록 조회, 생성, 수정, 삭제 API
  src/controllers/TimeBlockController.ts
  src/dtos/TimeBlockDto.ts
  src/middleware/errorValidator.ts
  src/modules/responseMessage.ts
  src/services/TimeBlockService.ts
Labels: enhancement, feat, danna

#39 feat: 에러 핸들링 적용 및 cors 설정
  package.json
  src/config/RoutingConfig.ts
  src/config/index.ts
  src/controllers/DailyNoteController.ts
  src/controllers/PlanController.ts
  src/controllers/TimeBlockController.ts
  src/controllers/UserController.ts
  src/middleware/errorHandler.ts
  src/middleware/errorValidator.ts
  src/modules/responseMessage.ts
  src/modules/returnToSlackMessage.ts
  src/modules/slack.ts
  src/services/DailyNoteService.ts
  src/services/PlanService.ts
  yarn.lock
Labels: enhancement, m1njae, feat
